=== pwdypb/SlidePuzzle/src/main/resources/messages/MessageSchema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="messages">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="message" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                        <xs:attribute name="value" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== pwdypb/SlidePuzzle/src/main/resources/messages/en-EN.xml
<?xml version="1.0" encoding="UTF-8"?>
<messages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="MessageSchema.xsd">
    <!--LANGUAGES-->
    <message id="ENGLISH" value="English"/>
    <message id="HUNGARIAN" value="Hungarian"/>

    <!--MAIN MENU-->
    <message id="NEW_GAME" value="New game"/>
    <message id="LOAD_GAME" value="Load game"/>
    <message id="STATISTICS" value="Statistics"/>
    <message id="EXIT_GAME" value="Exit game"/>

    <message id="CHOOSE_DIFFICULTY" value="Choose a difficulty level"/>
    <message id="EASY" value="Easy"/>
    <message id="MEDIUM" value="Medium"/>
    <message id="HARD" value="Hard"/>
</messages>
